'use server'

import { headers } from 'next/headers'
import { APIError } from 'better-auth/api'
import { auth } from '@/lib/auth'
import { Code, ResponsePromise } from '@/types'

type Data = any //# Fix this...
export type LogOutResponsePromise = ResponsePromise<Data>
export type LogOut = () => LogOutResponsePromise
export type LogOutResolvedResponse = Awaited<LogOutResponsePromise>

/* ========================================================================

======================================================================== */
///////////////////////////////////////////////////////////////////////////
//
// ⚠️ Gotcha:
//
// For Next.js apps, using server-side auth.api.signIn() / auth.api.signOut()
// in server actions for user-initiated login/logout is an anti-pattern. Even
// with the nextCookies() plugin in auth.ts, you will run into client-side state
// sync issues. The UI will not update on the client without a manual refresh.
//
// Better Auth provides client methods specifically designed for React/Next.js that
// handle everything automatically. For actual login/logout triggered by users, always
// use the client-side methods. When ARE Server-Side Auth APIs Useful?
//
// In Next.js:
//
//   - auth.api.getSession() - Check auth in Server Components, API routes, middleware, server actions
//   - auth.api.signIn() / signOut() - Pretty much never in typical Next.js apps
//
// In non-React backends (Express, Fastify, etc.):
//
//   - auth.api.signIn() / signOut() - Absolutely, because there's no client-side session management
//
///////////////////////////////////////////////////////////////////////////

export const logout: LogOut = async () => {
  /* ======================
        Validation
  ====================== */

  try {
    // The result will be an object that looks like this: { success: boolean; }
    const result = await auth.api.signOut({
      headers: await headers()
    })

    return {
      code: 'OK',
      data: result, //! DC 2026 : This was null. I added it for now...
      message: 'Log out success.',
      success: true
    }
  } catch (err) {
    if (err instanceof APIError) {
      // ...
    }

    return {
      //# Fix this...
      // The code would likely only be present if the err was
      // generated by the custom UnverifiedEmailError().
      code: (err instanceof Error && 'code' in err && typeof err.code === 'string'
        ? err.code
        : 'INTERNAL_SERVER_ERROR') as Code,
      data: null,
      message: 'Invalid email or password. (Server)',
      success: false
    }
  }
}
